import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";
import LoaderWrapper from "@/components/ui/LoaderWrapper";
import { Smooch_Sans } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { Raleway } from "next/font/google";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-montserrat",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jetbrains",
});

export const metadata = {
  title: "Palqar",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
    apple: "/apple-touch-icon.png",
  },
};
const smoochSans = Smooch_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-smooch",
});
export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${smoochSans.variable} ${dmSans.variable} ${raleway.variable} ${inter.variable} ${jetbrains.variable}`}>
        <LoaderWrapper>
          <Header />
          {children}
          <Footer />
        </LoaderWrapper>
      </body>
    </html>
  );
}
